/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarDoticsRouteImport } from './routes/calendar[.]ics'
import { Route as DeskKeyRouteImport } from './routes/desk.$key'
import { Route as DeskKeyIndexRouteImport } from './routes/desk.$key.index'
import { Route as DeskKeyDoRouteImport } from './routes/desk.$key.do'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDoticsRoute = CalendarDoticsRouteImport.update({
  id: '/calendar.ics',
  path: '/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskKeyRoute = DeskKeyRouteImport.update({
  id: '/desk/$key',
  path: '/desk/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskKeyIndexRoute = DeskKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskKeyRoute,
} as any)
const DeskKeyDoRoute = DeskKeyDoRouteImport.update({
  id: '/do',
  path: '/do',
  getParentRoute: () => DeskKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar.ics': typeof CalendarDoticsRoute
  '/desk/$key': typeof DeskKeyRouteWithChildren
  '/desk/$key/do': typeof DeskKeyDoRoute
  '/desk/$key/': typeof DeskKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar.ics': typeof CalendarDoticsRoute
  '/desk/$key/do': typeof DeskKeyDoRoute
  '/desk/$key': typeof DeskKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar.ics': typeof CalendarDoticsRoute
  '/desk/$key': typeof DeskKeyRouteWithChildren
  '/desk/$key/do': typeof DeskKeyDoRoute
  '/desk/$key/': typeof DeskKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/calendar.ics' | '/desk/$key' | '/desk/$key/do' | '/desk/$key/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar.ics' | '/desk/$key/do' | '/desk/$key'
  id:
    | '__root__'
    | '/'
    | '/calendar.ics'
    | '/desk/$key'
    | '/desk/$key/do'
    | '/desk/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarDoticsRoute: typeof CalendarDoticsRoute
  DeskKeyRoute: typeof DeskKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar.ics': {
      id: '/calendar.ics'
      path: '/calendar.ics'
      fullPath: '/calendar.ics'
      preLoaderRoute: typeof CalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/$key': {
      id: '/desk/$key'
      path: '/desk/$key'
      fullPath: '/desk/$key'
      preLoaderRoute: typeof DeskKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/$key/': {
      id: '/desk/$key/'
      path: '/'
      fullPath: '/desk/$key/'
      preLoaderRoute: typeof DeskKeyIndexRouteImport
      parentRoute: typeof DeskKeyRoute
    }
    '/desk/$key/do': {
      id: '/desk/$key/do'
      path: '/do'
      fullPath: '/desk/$key/do'
      preLoaderRoute: typeof DeskKeyDoRouteImport
      parentRoute: typeof DeskKeyRoute
    }
  }
}

interface DeskKeyRouteChildren {
  DeskKeyDoRoute: typeof DeskKeyDoRoute
  DeskKeyIndexRoute: typeof DeskKeyIndexRoute
}

const DeskKeyRouteChildren: DeskKeyRouteChildren = {
  DeskKeyDoRoute: DeskKeyDoRoute,
  DeskKeyIndexRoute: DeskKeyIndexRoute,
}

const DeskKeyRouteWithChildren =
  DeskKeyRoute._addFileChildren(DeskKeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarDoticsRoute: CalendarDoticsRoute,
  DeskKeyRoute: DeskKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
